### ISSUE TITLE
Internet/wifi Connection connectivity

### ISSUE THREAD

**Issue by RaineHolgado** [RaineHolgado/Daily-Sillimanian-Beta#35]
Create a sample project
- Used riverpod statemanagement
- Listen or Stream internet connection dramatically

- Show snackbar status if connection is lost during runtime on using the app.
  Steps: turn on the wifi first after a minute on using the app turn off the wifi

- When the app is closed/minimize and the user went back to the app it should show another screen that there is no connection.
  Steps: turn off the wifi then open the app

- If possible can you detect slow internet connection?

References:
https://stacksecrets.com/flutter/listen-to-internet-connection-state-in-flutter-app
https://pub.dev/packages/connectivity_plus

Note: Connectivity package is deprecated use the Connectivity-plus

**Comment by TezadaConnect** [comment]
## ISSUE #26 
Made a sample data connectivity using connectivity and data_connection_checker package. Here's the link of the repo https://tinyurl.com/data-connectivity-checker, closing the issue.
